Fix bug in docker healthcheck

diff --git a/build/Dockerfile-EmbeddedDB b/build/Dockerfile-EmbeddedDB
--- a/build/Dockerfile-EmbeddedDB
+++ b/build/Dockerfile-EmbeddedDB
@@ -62,15 +62,21 @@ COPY ../build/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 RUN mkdir -p /var/run/supervisord
 RUN mkdir -p /var/log/supervisord
 
-# clean up apt-get
-RUN apt-get clean && rm -rf /var/lib/apt/lists
-
 # copy entrypoint
 COPY ../build/entrypoint.sh /usr/sbin/entrypoint.sh
 RUN chmod +x /usr/sbin/entrypoint.sh
 
 # volumes
 VOLUME /home/gaseous/.gaseous-server /var/lib/mysql
+
+# Install curl
+RUN apt-get install -y curl
+
+# clean up apt-get
+RUN apt-get clean && rm -rf /var/lib/apt/lists
+
+# Configure healthcheck
+HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 CMD curl --fail http://localhost:80/api/v1.1/HealthCheck || exit 1
 
 # start services
 ENTRYPOINT [ "/usr/sbin/entrypoint.sh" ]
